GET https://compass.jinritemai.com/compass_api/author/product/product_analysis/product_list?
begin_date=2024%2F12%2F24+00%3A00%3A00&end_date=2024%2F12%2F30+00%3A00%3A00&date_type=21&activity_id=&selected_index=pay_amt%2Cpay_combo_cnt%2Cproduct_show_cnt%2Clive_show_click_ratio%2Clive_order_ratio&query_condition=&_lid=164493761184&msToken=Bo3c57JGlBNm8Oxllijk4mx1Gd4CpZZaLP0lno0fofo7HDt8aHIhjSMNkgXj7iVR8VPNxIljPlHyoF6LPD41wRnlHWoH4xOVe1o_zDBFPv_8QERNdml6UUuCjDw%3D&a_bogus=DjRMQmgXdk2BXfu654cLfY3qIsa3YkoC0cODMDZuQnfSF639HMTL9exEN44vUA8jxs%2FgICYjy4hbO3OZrQV90qwf7Wko%2F2CZsg00cMl25xSi5ZvHCDuDntRF4kw4Feep5JV3EcvmoiKczbEk09Or4hqvPD3ScHhMH6StO9392962YKUlAFNQeGA9&verifyFp=verify_m5bwjo01_xiscxiin_jqJJ_4g1u_Auj5_QYorHvXd56Ap&fp=verify_m5bwjo01_xiscxiin_jqJJ_4g1u_Auj5_QYorHvXd56Ap
Accept: application/json